package s3

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/xml"
	"fmt"
	"io"
	"maps"
	"net"
	"net/http"
	"net/http/httptest"
	"sort"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/greeddj/go-galaxy/internal/galaxy/config"
	"github.com/greeddj/go-galaxy/internal/galaxy/helpers"
)

// bucketListKey is the pseudo object key countRequest/requestCount use for a
// bucket-level ListObjectsV2 request, which - unlike GET/PUT/HEAD/DELETE -
// has no per-object key of its own. It can never collide with a real object
// key, since every real key under this fake's buckets is a non-empty
// slash-delimited path.
const bucketListKey = "list-objects-v2"

// bucketDeleteObjectsKey is bucketListKey's counterpart for a Multi-Object
// Delete (POST ?delete) request.
const bucketDeleteObjectsKey = "delete-objects"

// fakeObject is one stored object: its body, the X-Amz-Meta-* headers it was
// last written with (captured verbatim, keyed by canonical header name), and
// the time it was last written, which stands in for S3's Last-Modified.
type fakeObject struct {
	modified time.Time
	meta     map[string]string
	etag     string
	data     []byte
}

// fakeETag mints a distinct entity tag per stored version. A real S3 ETag is
// the object's MD5 for a single-part upload, which would make two writes of
// identical bytes indistinguishable - and the lock protocol writes a JSON
// record whose fields can repeat within a clock second. The sequence number
// is what guarantees every write gets a new tag, which is the property a
// compare-and-swap test actually depends on.
func fakeETag(body []byte, modified time.Time, seq uint64) string {
	sum := sha256.Sum256(body)
	return fmt.Sprintf("%q", fmt.Sprintf("%x-%d-%d", sum[:8], modified.UnixNano(), seq))
}

// fakeS3 is a minimal in-memory, path-style S3 fake used to exercise Backend
// and Client against real HTTP round trips without a network dependency or
// SigV4 verification (the client always signs requests, but this fake never
// checks the Authorization header).
type fakeS3 struct {
	objects map[string]fakeObject
	// fails is keyed exactly like requests ("METHOD key"), plus a wildcard
	// entry keyed " key" (empty method) that matches any method for that
	// key. Keying by method (not by key alone) lets a test arm independent
	// rules for two different methods against the very same key at once -
	// e.g. a PUT that always reports precondition-failed together with a
	// HEAD that always reports not-found on the same lock object key.
	fails    map[string]*forcedFailure
	requests map[string]int
	// drips is keyed by object key, armed via dripGet: a matching GET never
	// finishes its body on its own (see driveDripGet).
	drips map[string]time.Duration
	// syntheticBodies is keyed by object key, armed via serveSyntheticBody:
	// a matching GET answers with that many generated bytes instead of a
	// stored object (see handleGet).
	syntheticBodies map[string]int64
	// headTokenSwaps is keyed by object key, armed via raceTokenOnNextHead:
	// the next HEAD served for that key rewrites the stored object's token
	// first, simulating another writer's PUT landing in between this call's
	// own write and its own follow-up HEAD.
	headTokenSwaps    map[string]string
	failDeleteObjects *deleteObjectsFailure
	lastDeleteHeaders http.Header
	bucket            string
	lastDeleteReq     deleteRequest
	deleteDelay       time.Duration
	mu                sync.Mutex
	// etagSeq numbers stored versions so no two writes share an entity tag.
	etagSeq           uint64
	ignoreIfNoneMatch bool
	// ignoreIfMatch simulates a backend that accepts a compare-and-swap PUT
	// without enforcing it, which is what Open's capability probe must catch.
	ignoreIfMatch bool
	// refuseIfMatch simulates a backend that answers every compare-and-swap
	// with 412, matching ETag or not - a plausible shape for one that parses
	// the header without implementing it. It is the inverse of ignoreIfMatch
	// and the only one of the three that a probe checking refusals alone would
	// pass: nothing about it looks permissive, and every reclaim on it would
	// simply never succeed.
	refuseIfMatch bool
	// suppressETag simulates a backend that stores objects but never names
	// their version on a read, leaving a caller nothing to swap against. It is
	// the other non-conforming shape the same probe must catch, and it is not
	// reducible to ignoreIfMatch: this one refuses the swap honestly rather
	// than accepting it without arbitration.
	suppressETag          bool
	oversizedList         bool
	oversizedDeleteResult bool
}

// deleteObjectsFailure is a fault-injection rule for handleDeleteObjects: it
// reports key as a single <Error> entry in the DeleteResult (with the given
// code/message) instead of deleting it, while every other key in the same
// batch is still deleted normally - simulating a real per-key partial
// failure that DeleteObjects can report even under an overall 200 status.
type deleteObjectsFailure struct {
	key     string
	code    string
	message string
}

// forcedFailure is a fault-injection rule matched by object key and HTTP
// method: while remaining is nonzero, a matching request receives status
// (and, if set, body) instead of the fake's normal response, and remaining
// is decremented (unless already negative, meaning "fail indefinitely"). It
// exists to force error branches - GET/HEAD/PUT/DELETE failures, optionally
// carrying an S3-style XML error document - that a conforming in-memory fake
// would otherwise never produce on its own.
type forcedFailure struct {
	body      []byte // optional response body written alongside status, e.g. an S3 <Error> document
	status    int
	remaining int
}

// newFakeS3 constructs an empty fake bucket store named "test". One
// instance must be created per test so state never leaks between parallel
// tests.
func newFakeS3() *fakeS3 {
	return &fakeS3{
		objects: make(map[string]fakeObject),
		bucket:  "test",
	}
}

// ServeHTTP routes requests to the bucket root or an object path.
func (f *fakeS3) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	root := "/" + f.bucket
	switch {
	case r.URL.Path == root:
		f.handleBucket(w, r)
	case strings.HasPrefix(r.URL.Path, root+"/"):
		key := strings.TrimPrefix(r.URL.Path, root+"/")
		f.handleObject(w, r, key)
	default:
		http.NotFound(w, r)
	}
}

// failNext arms a forced-failure rule for key: the next count requests to
// key matching method (or every method, if method == "") receive status
// instead of the fake's normal response. count == -1 fails every matching
// request indefinitely, until failNext is called again for the same
// key+method pair. Rules for different methods on the same key are
// independent: arming one for http.MethodPut does not replace or interact
// with one already armed for http.MethodHead on that same key.
func (f *fakeS3) failNext(key, method string, status, count int) {
	f.failNextWithBody(key, method, status, count, nil)
}

// failNextWithBody behaves like failNext but additionally arms a response
// body to be written alongside the forced status code - for example an S3
// <Error> XML document - so a test can assert that callers surface its Code
// and Message.
func (f *fakeS3) failNextWithBody(key, method string, status, count int, body []byte) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.fails == nil {
		f.fails = make(map[string]*forcedFailure)
	}
	f.fails[method+" "+key] = &forcedFailure{status: status, remaining: count, body: body}
}

// countRequest records that key received one request via method, counting
// every request that reaches an object handler regardless of whether a
// forced-failure rule matches it. It exists purely as an observability hook
// so a test can assert the exact number of attempts a retrying call made
// (via requestCount) rather than inferring it indirectly from a
// forcedFailure's remaining count.
func (f *fakeS3) countRequest(key, method string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.requests == nil {
		f.requests = make(map[string]int)
	}
	f.requests[method+" "+key]++
}

// requestCount reports how many requests key has received via method so
// far, as recorded by countRequest.
func (f *fakeS3) requestCount(key, method string) int {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.requests[method+" "+key]
}

// shouldFail reports whether the request for key+method matches an armed
// forced-failure rule, consuming one use of it (unless the rule fails
// indefinitely). It checks the method-specific rule first, falling back to
// a wildcard rule armed for every method on key (method == "" when armed),
// so a test can combine a method-specific rule and a wildcard rule - or two
// method-specific rules for different methods - on the same key at once. It
// returns the status and body to write; body is nil when none was armed. It
// locks mu itself; callers must not already hold mu.
func (f *fakeS3) shouldFail(key, method string) (int, []byte, bool) {
	f.mu.Lock()
	defer f.mu.Unlock()
	for _, k := range [2]string{method + " " + key, " " + key} {
		rule, ok := f.fails[k]
		if !ok || rule.remaining == 0 {
			continue
		}
		if rule.remaining > 0 {
			rule.remaining--
		}
		return rule.status, rule.body, true
	}
	return 0, nil, false
}

// handleBucket answers bucket-level requests: existence probes (HEAD) and
// listing (GET with list-type=2).
func (f *fakeS3) handleBucket(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodHead:
		// The bucket always exists in this fake, so ensureBucket's HEAD
		// probe succeeds and it never attempts to create the bucket.
		w.WriteHeader(http.StatusOK)
	case http.MethodGet:
		if r.URL.Query().Get("list-type") == "2" {
			f.handleList(w, r)
			return
		}
		w.WriteHeader(http.StatusOK)
	case http.MethodPost:
		if r.URL.Query().Has("delete") {
			f.handleDeleteObjects(w, r)
			return
		}
		w.WriteHeader(http.StatusMethodNotAllowed)
	default:
		w.WriteHeader(http.StatusMethodNotAllowed)
	}
}

// handleList renders a minimal ListObjectsV2 XML response for keys under
// the requested prefix. Pagination is not simulated: every matching key is
// returned in one page (IsTruncated is always false). When oversizedList is
// armed, the normal listing is skipped entirely in favor of
// writeOversizedList.
func (f *fakeS3) handleList(w http.ResponseWriter, r *http.Request) {
	f.countRequest(bucketListKey, http.MethodGet)

	f.mu.Lock()
	oversized := f.oversizedList
	f.mu.Unlock()
	if oversized {
		f.writeOversizedList(w)
		return
	}

	prefix := r.URL.Query().Get("prefix")

	f.mu.Lock()
	keys := make([]string, 0, len(f.objects))
	for key := range f.objects {
		if strings.HasPrefix(key, prefix) {
			keys = append(keys, key)
		}
	}
	f.mu.Unlock()
	sort.Strings(keys)

	var body strings.Builder
	body.WriteString(`<?xml version="1.0" encoding="UTF-8"?>`)
	body.WriteString(`<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">`)
	for _, key := range keys {
		body.WriteString("<Contents><Key>")
		body.WriteString(key)
		body.WriteString("</Key></Contents>")
	}
	body.WriteString("<IsTruncated>false</IsTruncated>")
	body.WriteString("</ListBucketResult>")

	w.Header().Set("Content-Type", "application/xml")
	w.WriteHeader(http.StatusOK)
	_, _ = io.WriteString(w, body.String())
}

// writeOversizedList streams a ListObjectsV2-shaped body well past
// helpers.S3ListMaxSize using a single reused chunk, so the fake itself
// never allocates anywhere near that size; only the cumulative transferred
// byte count grows across repeated writes of the same buffer. It stops as
// soon as a write fails, which is expected once the client's size-limited
// reader aborts the read and closes the response body after crossing the
// cap.
func (f *fakeS3) writeOversizedList(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "application/xml")
	w.WriteHeader(http.StatusOK)
	chunk := bytes.Repeat([]byte("a"), 64<<10)
	var written int64
	for written <= helpers.S3ListMaxSize {
		n, err := w.Write(chunk)
		written += int64(n)
		if err != nil {
			break
		}
	}
}

// handleDeleteObjects answers a Multi-Object Delete (POST ?delete) request:
// a forced failure armed via failNext(bucketDeleteObjectsKey, ...) takes
// precedence over everything below, exactly like the object-level handlers,
// so a test can drive deleteObjectsBatch's own transient-failure retry path.
// Absent that, it parses the <Delete> body via encoding/xml - never by
// string matching, so an object key carrying XML metacharacters round-trips
// as a single literal <Object> entry exactly like a conforming S3 endpoint
// would rather than being reinterpreted as extra markup - deletes every
// listed key that is not the armed failDeleteObjects key, and renders a
// Quiet-mode <DeleteResult> reporting only that one key (if any) as an
// <Error>. When oversizedDeleteResult is armed, the normal response is
// skipped entirely in favor of writeOversizedDeleteResult. The parsed
// request and its headers are captured for
// deleteObjectsRequest/deleteObjectsHeaders so a test can assert what
// deleteObjectsBatch actually sent.
func (f *fakeS3) handleDeleteObjects(w http.ResponseWriter, r *http.Request) {
	f.countRequest(bucketDeleteObjectsKey, http.MethodPost)
	if status, _, fail := f.shouldFail(bucketDeleteObjectsKey, http.MethodPost); fail {
		w.WriteHeader(status)
		return
	}

	body, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	var req deleteRequest
	if err := xml.Unmarshal(body, &req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	f.mu.Lock()
	f.lastDeleteReq = req
	f.lastDeleteHeaders = r.Header.Clone()
	oversized := f.oversizedDeleteResult
	fail := f.failDeleteObjects
	f.mu.Unlock()
	if oversized {
		f.writeOversizedDeleteResult(w)
		return
	}

	var result deleteResult
	f.mu.Lock()
	for _, obj := range req.Objects {
		if fail != nil && obj.Key == fail.key {
			result.Errors = append(result.Errors, deleteError{Key: fail.key, Code: fail.code, Message: fail.message})
			continue
		}
		delete(f.objects, obj.Key)
	}
	f.mu.Unlock()

	payload, err := xml.Marshal(result)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/xml")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append([]byte(xml.Header), payload...))
}

// writeOversizedDeleteResult streams a DeleteResult-shaped body well past
// helpers.S3ListMaxSize using a single reused chunk, mirroring
// writeOversizedList, so a test can drive deleteObjectsBatch's size-limited
// response read into rejecting an oversized body.
func (f *fakeS3) writeOversizedDeleteResult(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "application/xml")
	w.WriteHeader(http.StatusOK)
	chunk := bytes.Repeat([]byte("a"), 64<<10)
	var written int64
	for written <= helpers.S3ListMaxSize {
		n, err := w.Write(chunk)
		written += int64(n)
		if err != nil {
			break
		}
	}
}

// failDeleteObjectsFor arms handleDeleteObjects to report key as a single
// <Error> entry (with the given code/message) instead of deleting it.
func (f *fakeS3) failDeleteObjectsFor(key, code, message string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.failDeleteObjects = &deleteObjectsFailure{key: key, code: code, message: message}
}

// deleteObjectsRequest returns the most recently received Multi-Object
// Delete request body, so a test can assert exactly which <Object> entries
// deleteObjectsBatch sent.
func (f *fakeS3) deleteObjectsRequest() deleteRequest {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.lastDeleteReq
}

// deleteObjectsHeaders returns the most recently received Multi-Object
// Delete request's headers, so a test can assert deleteObjectsBatch signs
// and content-hashes the batch (Content-MD5, X-Amz-Content-Sha256,
// Content-Type) without re-deriving SigV4 verification in the fake.
func (f *fakeS3) deleteObjectsHeaders() http.Header {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.lastDeleteHeaders
}

// handleObject answers object-level requests: HEAD, GET, PUT, and DELETE.
func (f *fakeS3) handleObject(w http.ResponseWriter, r *http.Request, key string) {
	switch r.Method {
	case http.MethodHead:
		f.handleHead(w, key)
	case http.MethodGet:
		f.handleGet(w, r, key)
	case http.MethodPut:
		f.handlePut(w, r, key)
	case http.MethodDelete:
		f.handleDelete(w, r, key)
	default:
		w.WriteHeader(http.StatusMethodNotAllowed)
	}
}

// raceTokenOnNextHead arms a one-shot rewrite of the stored object's
// recorded token, applied the next time a HEAD request for key is served
// (see handleHead). It simulates another acquirer's write landing in the
// narrow window between this call's own successful create/reclaim PUT and
// its own follow-up ownership-verifying HEAD - the race claim (lock.go)
// exists specifically to detect. It fires exactly once: the swap is cleared
// as soon as it is applied, so a subsequent HEAD sees the rewritten token
// undisturbed rather than swapping again.
// serveSyntheticBody arms key's GET to answer 200 with size bytes generated
// on the fly, so a test can drive a body past a multi-hundred-megabyte
// ceiling without materializing it anywhere: not in the caller, not in this
// fake's own stored objects, and not on the wire in the upload direction,
// since no PUT is needed at all. An armed key shadows any stored object of
// the same name rather than merging with it, and nothing is written into
// f.objects, so the fake's publish-immutable invariant for stored objects is
// untouched.
func (f *fakeS3) serveSyntheticBody(key string, size int64) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.syntheticBodies == nil {
		f.syntheticBodies = make(map[string]int64)
	}
	f.syntheticBodies[key] = size
}

// writeSyntheticBody streams EXACTLY size bytes of filler using one reused
// chunk, trimming the final chunk rather than overshooting to the next chunk
// boundary. The exactness is load-bearing, not tidiness: a caller arms this
// to sit one byte on a particular side of a size ceiling, and a body that
// rounded up to the next 64 KiB would trip that ceiling whether or not the
// armed count crossed it, making the ceiling untestable from here.
//
// It stops early on the first write error - which is what a reader aborting
// at its own size ceiling produces - so the fake stops as soon as the client
// has seen enough rather than pushing the whole body first. No Content-Length
// is declared: the body is deliberately allowed to end early, and announcing
// a length this handler may not fulfill would only change how net/http tears
// the connection down.
func writeSyntheticBody(w http.ResponseWriter, contentType string, size int64) {
	w.Header().Set("Content-Type", contentType)
	w.WriteHeader(http.StatusOK)
	const chunkSize = 64 << 10
	chunk := bytes.Repeat([]byte("a"), chunkSize)
	for remaining := size; remaining > 0; {
		next := chunk
		if remaining < chunkSize {
			next = chunk[:remaining]
		}
		n, err := w.Write(next)
		remaining -= int64(n)
		if err != nil {
			break
		}
	}
}

func (f *fakeS3) raceTokenOnNextHead(key, token string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.headTokenSwaps == nil {
		f.headTokenSwaps = make(map[string]string)
	}
	f.headTokenSwaps[key] = token
}

// storeLockObject writes a lock object directly into the fake's object map,
// carrying exactly the two X-Amz-Meta-* headers the lock protocol reads back
// (token and deadline) and a fresh Last-Modified. It bypasses HTTP on
// purpose: the tests that use it place a competing acquirer's write at an
// exact point in another acquirer's request sequence - from inside a handler
// that has just served a request, or between two requests of an in-flight
// reclaim - and a real PUT would add a round trip of its own, and its own
// entry in the request counters, right where the ordering is being set up.
//
// Like every other write path here it publishes a fresh meta map rather than
// mutating a stored one, so handleHead and handleGet can still read obj.meta
// after releasing f.mu without racing this call.
//
// It mints an ETag exactly as handlePut does, because the lock protocol reads
// one back for every object it intends to swap against: an object stored here
// without one would report a HEAD that names no version, which reclaimIfExpired
// refuses outright, and every fixture seeding an expired holder this way would
// then measure that refusal instead of the swap it meant to drive. A distinct
// ETag per call is also what makes a write installed behind another acquirer's
// HEAD observable as a version change rather than only as a token change.
func (f *fakeS3) storeLockObject(key, token string, deadline time.Time) {
	f.mu.Lock()
	defer f.mu.Unlock()
	stored := fakeObject{
		meta: map[string]string{
			"X-Amz-Meta-Token":    token,
			"X-Amz-Meta-Deadline": deadline.UTC().Format(time.RFC3339),
		},
		modified: time.Now(),
	}
	stored.etag = fakeETag(nil, stored.modified, f.nextETagSeq())
	f.objects[key] = stored
}

// dropObject removes an object from the fake's map directly, standing in for a
// holder releasing its lock at an exact point in another acquirer's request
// sequence. It bypasses HTTP for the same reason storeLockObject does.
func (f *fakeS3) dropObject(key string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	delete(f.objects, key)
}

// handleHead reports the stored object's metadata headers and Last-Modified
// verbatim, or 404 if absent. This backs the lock protocol's HEAD-only reads
// (token/deadline verification never needs to transfer the body). A forced
// failure armed via failNext takes precedence over the normal response; a
// swap armed via raceTokenOnNextHead is applied to the stored object before
// this response is built.
func (f *fakeS3) handleHead(w http.ResponseWriter, key string) {
	f.countRequest(key, http.MethodHead)
	// The body (if any) is deliberately not written here: real HTTP HEAD
	// responses carry no entity body, and net/http's server elides one even
	// if a handler attempts to write it, so arming a body on a HEAD rule
	// would never reach the client anyway.
	if status, _, fail := f.shouldFail(key, http.MethodHead); fail {
		w.WriteHeader(status)
		return
	}
	f.mu.Lock()
	obj, ok := f.objects[key]
	if ok {
		if token, swap := f.headTokenSwaps[key]; swap {
			// Every write path publishes a fresh meta map rather than
			// mutating one already stored in f.objects (handlePut ->
			// captureMeta builds a new map on every PUT) - the invariant
			// that lets handleHead/handleGet read obj.meta in
			// writeObjectHeaders after releasing f.mu without racing a
			// concurrent writer on the same map. This swap upholds that
			// invariant the same way: it clones obj.meta into a fresh map,
			// applies the swapped token there, and only then replaces the
			// stored fakeObject - it never writes through the old map.
			fresh := maps.Clone(obj.meta)
			fresh["X-Amz-Meta-Token"] = token
			obj.meta = fresh
			f.objects[key] = obj
			delete(f.headTokenSwaps, key)
		}
	}
	withETag := !f.suppressETag
	f.mu.Unlock()
	if !ok {
		w.WriteHeader(http.StatusNotFound)
		return
	}
	writeObjectHeaders(w.Header(), obj, withETag)
	w.WriteHeader(http.StatusOK)
}

// handleGet returns the stored object's metadata headers and body verbatim,
// or 404 if absent. A forced failure armed via failNext/failNextWithBody
// takes precedence over the normal response, and a drip armed via dripGet
// takes precedence over the normal body (see driveDripGet).
func (f *fakeS3) handleGet(w http.ResponseWriter, r *http.Request, key string) {
	f.countRequest(key, http.MethodGet)
	if status, body, fail := f.shouldFail(key, http.MethodGet); fail {
		w.WriteHeader(status)
		if len(body) > 0 {
			_, _ = w.Write(body)
		}
		return
	}
	f.mu.Lock()
	syntheticSize, synthetic := f.syntheticBodies[key]
	obj, ok := f.objects[key]
	interval, dripping := f.drips[key]
	withETag := !f.suppressETag
	f.mu.Unlock()
	if synthetic {
		writeSyntheticBody(w, "application/json", syntheticSize)
		return
	}
	if !ok {
		w.WriteHeader(http.StatusNotFound)
		return
	}
	writeObjectHeaders(w.Header(), obj, withETag)
	w.WriteHeader(http.StatusOK)
	if dripping {
		driveDripGet(w, r, interval)
		return
	}
	_, _ = w.Write(obj.data)
}

// dripGet arms a per-key drip on key's next GET (and every one after, since
// this fake has no notion of a fault Count): once the object's real headers
// and 200 status are written, the response body never actually arrives -
// driveDripGet writes one filler byte per interval instead, flushed onto the
// wire, forever, until the request's context ends. This models a degraded or
// hostile object-store endpoint whose GET keeps making genuine (if glacial)
// progress and so never trips a read-inactivity watchdog, the same shape
// fakegalaxy.Fault.DripInterval models for a Galaxy server.
func (f *fakeS3) dripGet(key string, interval time.Duration) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.drips == nil {
		f.drips = make(map[string]time.Duration)
	}
	f.drips[key] = interval
}

// driveDripGet writes a single filler byte per interval, flushed onto the
// wire, until r's context is done - enactFault's DripInterval arm in
// internal/testing/fakegalaxy mirrors this exact shape for a JSON Galaxy
// endpoint. The object's real Content-Length is never set here (handleGet's
// caller wrote only the headers and status before calling this), so the
// connection is served chunked and a client can never infer completion from
// a declared length.
func driveDripGet(w http.ResponseWriter, r *http.Request, interval time.Duration) {
	flusher, _ := w.(http.Flusher)
	for {
		if _, err := w.Write([]byte{' '}); err != nil {
			return
		}
		if flusher != nil {
			flusher.Flush()
		}
		select {
		case <-r.Context().Done():
			return
		case <-time.After(interval):
		}
	}
}

// nextETagSeq returns the next version number for a stored object. The caller
// already holds mu, which is where every write to the object map happens.
func (f *fakeS3) nextETagSeq() uint64 {
	f.etagSeq++
	return f.etagSeq
}

// handlePut stores the request body and its X-Amz-Meta-* headers under key,
// honoring both conditional headers the distributed lock uses. If-None-Match:
// * ("create if absent") fails with 412 when the key already exists. If-Match:
// <etag> ("compare and swap") answers the two statuses S3 itself distinguishes
// here: 412 when the key exists under a different ETag, and 404 when the key is
// absent entirely, since a swap names a version of an object rather than the
// bucket. Answering 412 for both would hide the arm reclaimIfExpired reads as
// "the holder released between our HEAD and our swap".
//
// ignoreIfNoneMatch simulates a non-conforming backend that overwrites
// regardless of the create-if-absent header; ignoreIfMatch does the same for
// the swap, which is what lets a test drive Open's own capability probe. A
// forced failure armed via failNext takes precedence over all of that (e.g. to
// simulate another writer's create winning a race, regardless of what this
// fake's own object map holds).
func (f *fakeS3) handlePut(w http.ResponseWriter, r *http.Request, key string) {
	f.countRequest(key, http.MethodPut)
	body, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if status, failBody, fail := f.shouldFail(key, http.MethodPut); fail {
		w.WriteHeader(status)
		if len(failBody) > 0 {
			_, _ = w.Write(failBody)
		}
		return
	}

	f.mu.Lock()
	defer f.mu.Unlock()
	if status, refused := f.conditionalRefusal(r, key); refused {
		w.WriteHeader(status)
		return
	}
	stored := fakeObject{
		data:     body,
		meta:     captureMeta(r.Header),
		modified: time.Now(),
	}
	stored.etag = fakeETag(body, stored.modified, f.nextETagSeq())
	f.objects[key] = stored
	w.Header().Set("ETag", stored.etag)
	w.WriteHeader(http.StatusOK)
}

// conditionalRefusal evaluates a PUT's conditional headers against what is
// stored, reporting the status to answer with and whether the write is refused
// at all. The caller already holds mu.
//
// It is split out of handlePut rather than inlined so the write path stays one
// statement per outcome; the two conditions are independent rules, and a
// request carrying neither falls through both.
func (f *fakeS3) conditionalRefusal(r *http.Request, key string) (int, bool) {
	if !f.ignoreIfNoneMatch && r.Header.Get("If-None-Match") == "*" {
		if _, exists := f.objects[key]; exists {
			return http.StatusPreconditionFailed, true
		}
	}
	want := r.Header.Get("If-Match")
	if want == "" || f.ignoreIfMatch {
		return 0, false
	}
	current, exists := f.objects[key]
	switch {
	case f.refuseIfMatch, exists && current.etag != want:
		return http.StatusPreconditionFailed, true
	case !exists:
		return http.StatusNotFound, true
	}
	return 0, false
}

// captureMeta extracts the X-Amz-Meta-* headers from an incoming request,
// keyed by their canonical header name, so handleHead/handleGet can echo
// them back verbatim on later reads.
func captureMeta(header http.Header) map[string]string {
	meta := make(map[string]string, len(header))
	for name, values := range header {
		if len(values) == 0 || !strings.HasPrefix(strings.ToLower(name), "x-amz-meta-") {
			continue
		}
		meta[name] = values[0]
	}
	return meta
}

// writeObjectHeaders sets obj's captured metadata headers plus a
// Last-Modified timestamp and, when withETag says so, the object's ETag,
// mirroring what a real S3 HEAD or GET response carries. The ETag is what the
// lock's reclaim conditions its compare-and-swap on, which is why withholding
// it is a shape worth driving: a backend that answers reads without naming a
// version is one the protocol has to refuse rather than guess around.
//
// withETag is a parameter rather than a read of f.suppressETag because this
// runs after handleHead/handleGet have released f.mu, so reading the field
// here would race a test arming it mid-run; the caller samples it inside its
// own critical section instead.
func writeObjectHeaders(header http.Header, obj fakeObject, withETag bool) {
	for name, value := range obj.meta {
		header.Set(name, value)
	}
	header.Set("Last-Modified", obj.modified.UTC().Format(http.TimeFormat))
	if obj.etag != "" && withETag {
		header.Set("ETag", obj.etag)
	}
}

// setSuppressETag arms (or disarms) the ETag-withholding shape mid-run, under
// mu, so a fixture can let Open's own probe pass and only then take the
// guarantee away.
func (f *fakeS3) setSuppressETag(suppress bool) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.suppressETag = suppress
}

// handleDelete removes the object, always reporting success like S3 does
// even when the key is already absent. If deleteDelay is set, it first
// waits that long - or until the request's context is done, whichever
// comes first - so a test can make DELETE outlast a caller's bounded
// context and observe the resulting timeout. A forced failure armed via
// failNext takes precedence over both of those behaviors.
func (f *fakeS3) handleDelete(w http.ResponseWriter, r *http.Request, key string) {
	f.countRequest(key, http.MethodDelete)
	if status, body, fail := f.shouldFail(key, http.MethodDelete); fail {
		w.WriteHeader(status)
		if len(body) > 0 {
			_, _ = w.Write(body)
		}
		return
	}
	f.mu.Lock()
	delay := f.deleteDelay
	f.mu.Unlock()
	if delay > 0 {
		timer := time.NewTimer(delay)
		defer timer.Stop()
		select {
		case <-r.Context().Done():
			http.Error(w, r.Context().Err().Error(), http.StatusGatewayTimeout)
			return
		case <-timer.C:
		}
	}

	f.mu.Lock()
	delete(f.objects, key)
	f.mu.Unlock()
	w.WriteHeader(http.StatusNoContent)
}

// newTestBackend starts a fake S3 server and returns a Backend configured
// to talk to it in path-style mode. SigV4 signatures are computed by the
// real client but never verified by the fake.
func newTestBackend(t *testing.T) *Backend {
	t.Helper()
	return newTestBackendWithFake(t, newFakeS3())
}

// newTestBackendAndFake behaves like newTestBackend but also returns the
// *fakeS3 backing it, so a test can arm fault injection via failNext or
// failNextWithBody against the same server the returned Backend talks to.
func newTestBackendAndFake(t *testing.T) (*Backend, *fakeS3) {
	t.Helper()
	fake := newFakeS3()
	return newTestBackendWithFake(t, fake), fake
}

// newNonConformingTestBackend starts a fake S3 server with
// ignoreIfNoneMatch set, simulating a backend that does not enforce
// conditional PUT, and returns a Backend pointed at it.
func newNonConformingTestBackend(t *testing.T) *Backend {
	t.Helper()
	fake := newFakeS3()
	fake.ignoreIfNoneMatch = true
	return newTestBackendWithFake(t, fake)
}

// newTestBackendWithFake starts fake as an httptest server and returns a
// Backend configured to talk to it in path-style mode. SigV4 signatures are
// computed by the real client but never verified by the fake.
func newTestBackendWithFake(t *testing.T, fake *fakeS3) *Backend {
	t.Helper()

	srv := httptest.NewServer(fake)
	t.Cleanup(srv.Close)

	cfg := config.S3CacheConfig{
		Endpoint:  srv.URL,
		Bucket:    fake.bucket,
		Region:    "us-east-1",
		AccessKey: "x",
		SecretKey: config.NewSecret("y"),
		PathStyle: true,
		Enabled:   true,
	}
	backend, err := New(cfg, srv.Client(), t.TempDir())
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	return backend
}

// newAcceptingNeverRespondingListener starts a live local TCP listener that
// accepts every connection and drains what it reads, but never writes a
// response, so a caller waiting on response headers gets exactly that: a
// connection, and then silence. It is shared across this package's test
// files, each pointing it at a different consumer: Client.do's own
// response-header-timeout row (cache_backend_classification_test.go, which
// also uses it for a dial-timeout row that never actually reaches the accept
// loop before its own deadline fires), the distributed lock's wait-ceiling
// classification (lock_test.go, simulating a live but unresponsive S3
// endpoint during acquisition), and getObject's own retry-count assertion
// against a repeated response-header timeout (client_test.go). The returned
// counter increments once per accepted connection, so a caller can assert
// exactly how many attempts a retrying request made against this listener
// without needing its own separate bookkeeping.
func newAcceptingNeverRespondingListener(t *testing.T) (net.Listener, *atomic.Int32) {
	t.Helper()
	var lc net.ListenConfig
	ln, err := lc.Listen(context.Background(), "tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("net.Listen: %v", err)
	}
	// done gates when an accepted connection is finally closed: closing it the
	// instant the request is drained would abort the connection out from under
	// a caller still waiting on response headers, turning the intended timeout
	// into an immediate EOF/connection-reset instead.
	done := make(chan struct{})
	t.Cleanup(func() {
		close(done)
		_ = ln.Close()
	})

	var accepted atomic.Int32
	go func() {
		for {
			conn, err := ln.Accept()
			if err != nil {
				return
			}
			accepted.Add(1)
			go func(c net.Conn) {
				buf := make([]byte, 4096)
				_, _ = c.Read(buf) // drain the request; a response is never written.
				<-done             // hold the connection open, silently, until the test cleans up.
				_ = c.Close()
			}(conn)
		}
	}()

	return ln, &accepted
}
