package gzipstream

// This file is a structural, source-auditing test, the same shape
// internal/proseaudit, internal/lockaudit and internal/galaxy/archive's own
// probe-decompressor gate already use elsewhere in this module: it parses the
// module's own tree and checks a property of its AST rather than driving code
// at runtime.
//
// It exists because per-call-site reasoning already failed here, in public.
// The defect this package answers reached five readers, and a review that went
// looking for the word pgzip found four: internal/cache/s3 imported the
// library as `gzip "github.com/klauspost/pgzip"`, so the fifth reader read
// like the standard library's own and no search for that word could see it.
// This gate resolves the import path instead of the identifier, so no alias
// can hide the next one.
//
// What it audits is an allow-list of the members another package may name, not
// a list of the ones it may not - see pgzipWriterAPI for the two constructions
// that a blocklist of the reader constructors was measured missing.

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// pgzipImportPath is the library whose reading side this package holds a
// monopoly on.
const pgzipImportPath = "github.com/klauspost/pgzip"

// pgzipDotImport is what pgzipLocalName reports for a file that dot-imports
// the library: the selector search cannot see through one, so it is treated as
// a use rather than as an absence.
const pgzipDotImport = "."

// pgzipLocalName returns the identifier file bound klauspost/pgzip to, "" when
// it does not import it at all or imports it blank (which binds no name and so
// can reach nothing), and pgzipDotImport for a dot import.
//
// Resolving the path rather than trusting the spelling "pgzip" is the whole
// point of this gate: the same call reads as gzip.NewReader, pg.NewReader or
// anything else the importer chose.
func pgzipLocalName(file *ast.File) string {
	for _, imp := range file.Imports {
		path, err := strconv.Unquote(imp.Path.Value)
		if err != nil || path != pgzipImportPath {
			continue
		}
		switch {
		case imp.Name == nil:
			return "pgzip" // the package's own name
		case imp.Name.Name == "_":
			return ""
		default:
			return imp.Name.Name
		}
	}
	return ""
}

// moduleRoot walks up from this package's directory to the one holding go.mod,
// so the walk below covers the module rather than wherever the test binary
// happens to run.
func moduleRoot(t *testing.T) string {
	t.Helper()

	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("working directory: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("no go.mod above %s", dir)
		}
		dir = parent
	}
}

// TestPgzipBeyondItsWriterAPIIsThisPackagesAlone walks every non-test Go file
// in the module and fails on any member of klauspost/pgzip outside
// pgzipWriterAPI named outside this package.
//
// Test files are out of scope on purpose: a fixture builder that opens pgzip
// directly to prove something about pgzip is not a reader of artifact bytes,
// and gating them would make this file's own controls unwritable.
//
// vendor/ is skipped because it is not this module's source - it is
// git-ignored, regenerated by `just deps`, and absent in CI entirely, so a
// gate over it would be a gate over a directory half the machines running it
// do not have.
//
// TestPgzipUsesSeeEveryConstructionThatReachesAReader is this gate's positive
// control and is not optional: a detector that finds nothing passes a monopoly
// gate perfectly.
//
// Killing mutation, run: restoring internal/cache/s3/backend.go's original
// `gzip "github.com/klauspost/pgzip"` import and its gzip.NewReader call - the
// fifth reader, in the shape that hid it - fails this test with
//
//	monopoly_test.go:130: internal/cache/s3/backend.go reaches [gzip.NewReader]; only internal/gzipstream may read through pgzip
func TestPgzipBeyondItsWriterAPIIsThisPackagesAlone(t *testing.T) {
	t.Parallel()

	root := moduleRoot(t)
	fset := token.NewFileSet()
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		switch {
		case err != nil:
			return err
		case d.IsDir():
			return skipUnauditedDir(root, path, d)
		case !auditableFile(root, path):
			return nil
		}
		file, parseErr := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
		if parseErr != nil {
			return parseErr
		}
		if uses := pgzipUsesOutsideTheWriterAPI(file); len(uses) > 0 {
			rel, _ := filepath.Rel(root, path)
			t.Errorf("%s reaches %v; only internal/gzipstream may read through pgzip", rel, uses)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walking %s: %v", root, err)
	}
}

// skipUnauditedDir prunes the directories this gate does not read: vendor/ and
// anything dot-prefixed, both of which are outside this module's own source.
func skipUnauditedDir(root, path string, d os.DirEntry) error {
	if path != root && (d.Name() == "vendor" || strings.HasPrefix(d.Name(), ".")) {
		return filepath.SkipDir
	}
	return nil
}

// auditableFile reports whether path is a non-test Go file outside this
// package - the set the monopoly covers.
func auditableFile(root, path string) bool {
	if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
		return false
	}
	rel, err := filepath.Rel(root, path)
	return err == nil && filepath.Dir(rel) != filepath.Join("internal", "gzipstream")
}

// The fixtures the control below parses, spelled out here rather than inside
// it so that the test reads as the table it is. Each one is a construction
// that reaches, or deliberately does not reach, a pgzip reader.
const (
	aliasedPgzipFixture = `package fixture

import (
	"io"

	gzip "github.com/klauspost/pgzip"
)

func open(r io.Reader) { _, _ = gzip.NewReader(r) }
`
	plainPgzipFixture = `package fixture

import (
	"io"

	"github.com/klauspost/pgzip"
)

func open(r io.Reader) { _, _ = pgzip.NewReaderN(r, 1024, 1) }
`
	functionValuePgzipFixture = `package fixture

import (
	"io"

	"github.com/klauspost/pgzip"
)

var ctor = pgzip.NewReader

func open(r io.Reader) { _, _ = ctor(r) }
`
	resetPgzipFixture = `package fixture

import (
	"io"

	"github.com/klauspost/pgzip"
)

func open(r io.Reader) {
	var z pgzip.Reader
	_ = z.Reset(r)
}
`
	dotImportPgzipFixture = `package fixture

import (
	"io"

	. "github.com/klauspost/pgzip"
)

func open(r io.Reader) { _, _ = NewReader(r) }
`
	blankImportPgzipFixture = `package fixture

import (
	_ "github.com/klauspost/pgzip"
)
`
	writerOnlyPgzipFixture = `package fixture

import (
	"io"

	"github.com/klauspost/pgzip"
)

func compress(w io.Writer) { _ = pgzip.NewWriter(w) }
`
	stdlibGzipFixture = `package fixture

import (
	"compress/gzip"
	"io"
)

func open(r io.Reader) { _, _ = gzip.NewReader(r) }
`
)

// TestPgzipUsesSeeEveryConstructionThatReachesAReader is the positive control
// named on the gate above, carrying its negative controls in the same table:
// the detector must find every construction that reaches a pgzip reader, and
// must NOT find the two that reach none.
//
// The rows are one per construction rather than one per spelling. An aliased
// import is the shape that hid the fifth reader; a function value and a
// zero-value Reset are the two that were measured slipping past the blocklist
// this gate replaced (see pgzipWriterAPI); a dot import is reported on the
// import alone, since no selector search can see through one; and a blank
// import binds no name, so nothing can be reached through it.
//
// The last two rows are what stop this from being a gate that merely reports
// every mention of the word: pgzip.NewWriter is the call internal/cache/s3
// makes on this very seam and must stay silent, and the standard library's own
// gzip under the identical identifier must stay silent too.
//
// Two killing mutations pin this table, both run against this file with the
// detector where it now sits, and between them they pin the two rows naming
// the constructions the blocklist this gate replaced could not see.
//
// Restoring that blocklist in full - narrowing the search back to a call's Fun
// and testing the name against "NewReader"/"NewReaderN" - passes every other
// row and fails both:
//
//	monopoly_test.go:308: pgzipUsesOutsideTheWriterAPI(a constructor held as a function value) = [], want 1 use(s)
//	monopoly_test.go:308: pgzipUsesOutsideTheWriterAPI(a zero value turned into a reader by Reset) = [], want 1 use(s)
//
// Restoring its name test alone - `sel.Sel.Name != "NewReader" &&
// sel.Sel.Name != "NewReaderN"` in place of the allow-list call, three lines
// for three - leaves the search over every selector standing and fails the
// Reset row by itself:
//
//	monopoly_test.go:308: pgzipUsesOutsideTheWriterAPI(a zero value turned into a reader by Reset) = [], want 1 use(s)
//
// The pair is a differential, not two independent checks: the second mutation
// is the first one's name test without its search narrowing, so a row that
// survives the second and dies to the first is pinned to that narrowing
// alone. The function-value row is that row, which is why both are quoted.
func TestPgzipUsesSeeEveryConstructionThatReachesAReader(t *testing.T) {
	t.Parallel()

	for _, tt := range []struct {
		name string
		src  string
		want int
	}{
		{name: "an aliased pgzip import", src: aliasedPgzipFixture, want: 1},
		{name: "an unaliased pgzip import", src: plainPgzipFixture, want: 1},
		{name: "a constructor held as a function value", src: functionValuePgzipFixture, want: 1},
		{name: "a zero value turned into a reader by Reset", src: resetPgzipFixture, want: 1},
		{name: "a dot import", src: dotImportPgzipFixture, want: 1},
		{name: "a blank import", src: blankImportPgzipFixture, want: 0},
		{name: "the writer this seam is allowed", src: writerOnlyPgzipFixture, want: 0},
		{name: "the standard library under the same identifier", src: stdlibGzipFixture, want: 0},
	} {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			file, err := parser.ParseFile(token.NewFileSet(), "fixture.go", tt.src, parser.SkipObjectResolution)
			if err != nil {
				t.Fatalf("parsing the fixture: %v", err)
			}
			if got := pgzipUsesOutsideTheWriterAPI(file); len(got) != tt.want {
				t.Fatalf("pgzipUsesOutsideTheWriterAPI(%s) = %v, want %d use(s)", tt.name, got, tt.want)
			}
		})
	}
}

// The detector sits below the tests that drive it, which is this file's own
// arrangement rather than Go's. The two killing mutations the control above
// quotes are both rewrites of the detector, and the first of them is longer
// than what it replaces; anything under a growing mutation moves, so a line
// number quoted in that paragraph would come to name a line other than the
// one that produced the message. With nothing under it to move, a mutation of
// the detector may grow to any length and every citation still resolves.

// pgzipWriterAPI reports whether name is one of the members of klauspost/pgzip
// a package outside this one may name: the allow-list this gate is built on.
// Anything else is reported, including whatever a future release adds.
//
// It is an allow-list because the obvious blocklist - the two reader
// constructors, matched as a call's callee - is evadable in two ways that
// name neither of them, both measured against that form and both undetected
// by it. A function value, `var ctor = pgzip.NewReader` and then
// ctor(r), puts the selector somewhere other than a call's Fun. And a zero
// value plus Reset, `var z pgzip.Reader` and then z.Reset(src), builds a
// complete reader with no constructor at all: Reset sets z.multistream = true
// unconditionally, fills the block pool when it is nil, and parses the header
// (gunzip.go), so the result reads a two-member stream perfectly well - the
// recursion this package exists to replace, back in full. Naming the members
// that are safe is the one formulation that answers both without a rule per
// vector.
//
// The writer is what the allow-list keeps, because this package's subject is
// what a member of an INCOMING stream may be: a writer produces one member of
// this program's own making, and internal/cache/s3 compresses the snapshot it
// is about to upload through exactly that call without being a reader of
// anything.
func pgzipWriterAPI(name string) bool {
	return name == "NewWriter" || name == "NewWriterLevel"
}

// pgzipUsesOutsideTheWriterAPI reports, one string per use, how file reaches
// klauspost/pgzip outside pgzipWriterAPI.
//
// Every selector on the package is examined, in any position - a call's
// callee, a function value, a type - rather than only a call's callee, which
// is what makes the Reset vector visible: the method call itself is on an
// ordinary local variable and names no package, but the declaration that gives
// that variable its type cannot avoid naming one.
func pgzipUsesOutsideTheWriterAPI(file *ast.File) []string {
	local := pgzipLocalName(file)
	if local == "" {
		return nil
	}
	if local == pgzipDotImport {
		return []string{"dot-imports " + pgzipImportPath}
	}

	var uses []string
	ast.Inspect(file, func(n ast.Node) bool {
		if name, found := pgzipSelectorOutsideTheWriterAPI(n, local); found {
			uses = append(uses, local+"."+name)
		}
		return true
	})
	return uses
}

// pgzipSelectorOutsideTheWriterAPI reports the member of the package bound to
// local that n names, if n names one outside pgzipWriterAPI at all.
func pgzipSelectorOutsideTheWriterAPI(n ast.Node, local string) (string, bool) {
	sel, isSel := n.(*ast.SelectorExpr)
	if !isSel {
		return "", false
	}
	pkg, isIdent := sel.X.(*ast.Ident)
	if !isIdent || pkg.Name != local {
		return "", false
	}
	if pgzipWriterAPI(sel.Sel.Name) {
		return "", false
	}
	return sel.Sel.Name, true
}
